### ISSUE TITLE
support bluetooth ...

### ISSUE THREAD

**Issue by twocolors** [twocolors/esphome-native-api#2]
support bluetooth ...

https://esphome.io/components/bluetooth_proxy.html

**Comment by richardhopton** [comment]
I'd like this support too - do you have a discord or something where I can join?

**Comment by twocolors** [comment]
there is nothing, if you create I will join

**Comment by twocolors** [comment]
@richardhopton I'm sorry.

This is my mistake (accidental push when you did ble), I reverted the commit.

Thanks, I really appreciate your help.

**Comment by twocolors** [comment]
you can find me in https://discord.gg/uvYac5u

**Comment by richardhopton** [comment]
@twocolors can we close this issue now?

**Comment by twocolors** [comment]
@richardhopton thx
