### ISSUE TITLE
[Discovery] Crash in function if interface !== 0.0.0.0

### ISSUE THREAD

**Issue by DutchmanNL** [twocolors/esphome-native-api#28]
thank you solving discovery functionality.

I have one issue providing an interface, as system can have multiple network cards allowing to bind is an nice feature.

Using 0.0.0.0 as interface works well, 127.0.0.1 also has no issue (no devices found as expected)
```
discovery = new Discovery({interface: '0.0.0.0'});
```

When I  call the function with an interface ip address  I get an error:
```
discovery = new Discovery({interface: '192.168.10.107'});
```
<img width="769" alt="Screenshot 2023-12-02 at 13 51 01" src="https://github.com/twocolors/esphome-native-api/assets/7318445/76c87b08-ab67-432a-9ccf-63253ba1e867">
<img width="711" alt="Screenshot 2023-12-02 at 13 51 18" src="https://github.com/twocolors/esphome-native-api/assets/7318445/ae219ce2-a585-4b98-89c0-e1c9ad5d275b">

**Comment by twocolors** [comment]
more https://github.com/mafintosh/multicast-dns/issues/53#issuecomment-638365104
```
#!/usr/bin/env node

const Discovery = require('../lib/discovery.js');
Discovery({interface: '192.168.0.134', bind: '0.0.0.0'}).then(results => {
    console.log(results);
});
```
try git

**Comment by twocolors** [comment]
add support ``bind`` for discovery in ```1.2.7```

**Comment by DutchmanNL** [comment]
Will be able to test & confirm next week, on business travel currently 😢
