### ISSUE TITLE
support noise encryption and token auth?

### ISSUE THREAD

**Issue by janneman001** [twocolors/esphome-native-api#5]
Are you planning to implement noise encryption and token (key) auth?

**Comment by twocolors** [comment]
Oh , i not found noise “ Noise_NNpsk0_25519_ChaChaPoly_SHA256” for nodejs , if you can help “welcome” 

My knowledge is not enough to implement fast the protocol

**Comment by richardhopton** [comment]
How about https://github.com/nazar-pc/noise-c.wasm
